apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nextjs-app
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: nodejs
  params:
    - name: app-name
      value: express-buildah-proj
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/fabrizio-pietrucci-nextjs-app.git
    - name: image-repo
      value: quay.io/fabrizio_pietrucci/nextjs-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate: 
        spec: 
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
    - name: pipeline-shared-data
      volumeClaimTemplate: 
        spec: 
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce    
